### ISSUE TITLE
perlin noise generator gives unexpected results

### ISSUE THREAD

**Issue by redcodefinal** [Spooner/ruby-perlin#2]
Edit: Sorry, somehow my desciption edit didn't make it through

Perlin::Generator seems to break on powers of 10, always defaulting to 0.

p = Perlin::Generator.new(1.23, 0.03, 8)
=> #Perlin::Generator:0x00000001d8ef18
p[1,1]
=> 0.0
p[1.0,1.0]
=> 0.0
p[1.0,0.1]
=> -0.5970402359962463
p[0,0]
=> -0.025258755311369896
p[3,3]
=> -0.734154462814331
p[1,1]
=> 0.0
p[2,2]
=> -0.0007810739916749299
p[10,10]
=> 0.0
p[100,100]
=> 0.0
p[11,11]
=> -0.7398642301559448
p = Perlin::Generator.new(637, 0.03, 8)
=> #Perlin::Generator:0x00000001b81478
p[11,11]
=> -0.6352142095565796
p[1,1]
=> 0.0
p[100,100]
=> 0.0
p[111,111]
=> -0.02214318886399269

**Comment by Spooner** [comment]
Unexpected in what way?

**Comment by redcodefinal** [comment]
seems to always give 0 on x and y being powers of 10. [1,1] always comes back with 0.

>> p = Perlin::Generator.new(1.23, 0.03, 8)
=> #<Perlin::Generator:0x00000001d8ef18>
>> p[1,1]
=> 0.0
>> p[1.0,1.0]
=> 0.0
>> p[1.0,0.1]
=> -0.5970402359962463
>> p[0,0]
=> -0.025258755311369896
>> p[3,3]
=> -0.734154462814331
>> p[1,1]
=> 0.0
>> p[2,2]
=> -0.0007810739916749299
>> p[10,10]
=> 0.0
>> p[100,100]
=> 0.0
>> p[11,11]
=> -0.7398642301559448
>> p = Perlin::Generator.new(637, 0.03, 8)
=> #<Perlin::Generator:0x00000001b81478>
>> p[11,11]
=> -0.6352142095565796
>> p[1,1]
=> 0.0
>> p[100,100]
=> 0.0
>> p[111,111]
=> -0.02214318886399269

**Comment by bil-bas** [comment]
I have no idea why you would be having this happen. As far as I can see, the numbers seem to be consistent with what they used to be and when using examples/gosu.rb I can see them following in a typical noise pattern!

(I updated the rspec tests to 3.3 syntax, and fixed some of them, so it would be easier to test any problems - released as v0.2.2).

**Comment by sol-vin** [comment]
Did you try the same steps in IRB?

**Comment by sol-vin** [comment]
Hi @Spooner, I am using your perlin gem in a game I'm making with Gosu and I've still had this issue happen. I'd like to provide as many details as you need to hopefully track this down. I really like this gem and maybe something I have can help it get solved. 

I'm still having issues with IRB and perlin, here is an example.

``` ruby
2.3.0 :003 > require 'perlin'
 => true 
2.3.0 :004 > p = Perlin::Generator.new(1.24, 0.03, 8)
 => #<Perlin::Generator:0x00000000fdb7b8> 
2.3.0 :005 > p[0, 0]
 => -0.025258755311369896 
2.3.0 :006 > p[1, 1]                                                            
 => 0.0 
2.3.0 :007 > p[10, 1]
 => 0.0 
2.3.0 :008 > p[10, 10]
 => 0.0 
2.3.0 :009 > p[100, 100]
 => 0.0 
2.3.0 :010 > p[100, 10]                                                         
 => 0.0 
2.3.0 :011 > p[100, 1]                                                          
 => 0.0 

```

I use your gem in a project that generates isometric worlds. There are some times it works great, other times it produces strange artefacts. Here is the [basic perlin world generation code](https://github.com/redcodefinal/isometric-world-generator/blob/master/lib/worlds/examples/perlin/basic_perlin_world.rb) which accesses methods defined in [PerlinHelper](https://github.com/redcodefinal/isometric-world-generator/blob/master/lib/helpers/perlin_helper.rb), a class I wrote to access perlin data in some special ways for my world generator. 

So far your gem has provided me with some [quality perlin noise shots](http://broken-kami.tumblr.com/post/143459274550/httpsgithubcomredcodefinalisometric-world-gen) However some times there are [artefacts](http://broken-kami.tumblr.com/post/143467689265/httpsgithubcomredcodefinalisometric-world-gen) that seem totally devoid of the smooth curves of perlin.

**Comment by sol-vin** [comment]
Hi, I found a fix for this, switching classic mode on seems to fix it.

**Comment by bil-bas** [comment]
Of course, that would work - completely different code (but slower and not
as nice noise pattern). Hope it suits you!
